### PR TITLE
Add an interface for adding shortcodes instead of the user memorizing #24

### PR DESCRIPTION
**Pull request by contactashish13**
Issue #24

### CODE REVIEW

**Comment by michaeltorbert** [comment]
@contactashish13 At first glance, this can be cleaned up a bit. The scripts and styles should be registered in admin_enqueue_scripts, not enqueued in every admin_head (admittedly this isn't done correctly in pre-existing code). 
Then they should be enqueued when needed. Surely there's something better than admin_head for all this...  either hooking into admin_head-post.php/post-new.php or something similar?

**Comment by contactashish13** [comment]
@michaeltorbert have added a check to ensure the resources load only on post/custom post/page screens

**Comment by wpsmort** [comment]
@contactashish13 I tested this and the UI needs some styling.  I also found that nothing happens when you click the Select Categories or Select Tags boxes.  Is that supposed to list the categories and tags?

**Comment by contactashish13** [comment]
@wpsmort I discussed the styling with @michaeltorbert and he said I could just add skeleton classes for your CSS expert to put in the styling.

As for the drop downs, both are auto complete. So you can either type in the tags/categories or select.

**Comment by contactashish13** [comment]
@wpsmort please check this video https://drive.google.com/file/d/0B_GLg3hHI3AzVkxZemw2WEI5LUU/view

**Comment by wpsmort** [comment]
Thanks @contactashish13 .  This is tested and is good.  

@michaeltorbert Do you want to review the code for this PR before or after the styling is completed?

**Pull request merged**
